/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.ostfalia.serp.project.api;

import de.ostfalia.serp.project.dto.Error;
import de.ostfalia.serp.project.dto.ProjectDTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-22T13:15:13.010093795+02:00[Europe/Berlin]")
@Validated
@Tag(name = "Projects", description = "Projects API")
public interface ProjectsApi {

    /**
     * POST /projects : Create a project
     *
     * @param projectDTO  (required)
     * @return Project created (status code 201)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "createProject",
        summary = "Create a project",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Project created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectDTO.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/projects",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ProjectDTO> createProject(
        @Parameter(name = "ProjectDTO", description = "", required = true) @Valid @RequestBody ProjectDTO projectDTO
    );


    /**
     * DELETE /projects/{id} : Delete a project
     *
     * @param id The ID of the project to delete (required)
     * @return Project deleted (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "deleteProject",
        summary = "Delete a project",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Project deleted"),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/projects/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteProject(
        @Parameter(name = "id", description = "The ID of the project to delete", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /projects/{id} : Get a project
     *
     * @param id The ID of the project to retrieve (required)
     * @return Project retrieved (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "getProjectById",
        summary = "Get a project",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Project retrieved", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectDTO.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/projects/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<ProjectDTO> getProjectById(
        @Parameter(name = "id", description = "The ID of the project to retrieve", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /projects : Get all projects
     *
     * @return Success (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "getProjects",
        summary = "Get all projects",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ProjectDTO.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/projects",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<ProjectDTO>> getProjects(
        
    );


    /**
     * GET /projects/consultant/{id} : Get projects by consultant ID
     *
     * @param id The ID of the consultant to retrieve projects for (required)
     * @return Projects retrieved (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "getProjectsByConsultant",
        summary = "Get projects by consultant ID",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Projects retrieved", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ProjectDTO.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/projects/consultant/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<ProjectDTO>> getProjectsByConsultant(
        @Parameter(name = "id", description = "The ID of the consultant to retrieve projects for", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /projects/{id} : Update a project
     *
     * @param id The ID of the project to update (required)
     * @param projectDTO  (required)
     * @return Project updated (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "updateProject",
        summary = "Update a project",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Project updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectDTO.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/projects/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ProjectDTO> updateProject(
        @Parameter(name = "id", description = "The ID of the project to update", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "ProjectDTO", description = "", required = true) @Valid @RequestBody ProjectDTO projectDTO
    );

}
