spring.application.name=entry-service
server.port=${PORT:8083}
debug=false

# =================================
# DATABASE (PostgreSQL)
# =================================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/entry_db
spring.datasource.username=${DB_USER:entry_user}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# =================================
# OPENAPI / SWAGGER
# =================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=de.ostfalia.serp.entry.controller

# =================================
# FIX LOADBALANCER DOCKER
# =================================
# On indique au service des temps où trouver les deux autres services
spring.cloud.discovery.client.simple.instances.project-service[0].uri=http://project-service:8084
spring.cloud.discovery.client.simple.instances.consultant-service[0].uri=http://consultant-service:8082

# =================================
# RÉSILIENCE (CIRCUIT BREAKER)
# =================================
management.health.circuitbreakers.enabled=true

# 1. Configuration pour le disjoncteur du Project Service
resilience4j.circuitbreaker.instances.projectServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.projectServiceCB.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.projectServiceCB.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.projectServiceCB.minimumNumberOfCalls=2

# 2. Configuration pour le disjoncteur du Consultant Service
resilience4j.circuitbreaker.instances.consultantServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.consultantServiceCB.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.consultantServiceCB.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.consultantServiceCB.minimumNumberOfCalls=2

# =================================
# LOGGING
# =================================
logging.level.org.springframework.web=INFO
logging.level.de.ostfalia.serp=DEBUG