spring.application.name=customer-service
server.port=${PORT:8081}
debug=false

# =================================
# DATABASE (PostgreSQL)
# =================================
# On utilise une variable d'env pour l'hôte. Par défaut 'localhost' pour ton IDE.
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/customer_db
spring.datasource.username=${DB_USER:customer_user}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# =================================
# OPENAPI / SWAGGER
# =================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=de.ostfalia.serp.customer.controller

# =================================
# LOGGING
# =================================
logging.level.org.springframework.web=INFO
logging.level.de.ostfalia.serp=DEBUG