/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.ostfalia.serp.entry.api;

import de.ostfalia.serp.entry.dto.EntryConsultantDTO;
import de.ostfalia.serp.entry.dto.EntryDTO;
import de.ostfalia.serp.entry.dto.EntryProjectDTO;
import de.ostfalia.serp.entry.dto.Error;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-17T13:44:58.413945039+02:00[Europe/Berlin]")
@Validated
@Tag(name = "Time", description = "Time bookings (entries) for a project and consultant")
public interface TimeApi {

    /**
     * POST /time/entries/{consultantId} : post an entry, time bookings for a consultant
     *
     * @param consultantId The ID of the consultant (required)
     * @param entryDTO  (required)
     * @return Project created (status code 201)
     */
    @Operation(
        operationId = "createEntry",
        summary = "post an entry, time bookings for a consultant",
        tags = { "Time" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Project created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EntryDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/time/entries/{consultantId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<EntryDTO> createEntry(
        @Parameter(name = "consultantId", description = "The ID of the consultant", required = true, in = ParameterIn.PATH) @PathVariable("consultantId") Long consultantId,
        @Parameter(name = "EntryDTO", description = "", required = true) @Valid @RequestBody EntryDTO entryDTO
    );


    /**
     * GET /time/entries : Gets all entries, time bookings
     *
     * @return Entries retrieved (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "getAllEntries",
        summary = "Gets all entries, time bookings",
        tags = { "Time" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Entries retrieved", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EntryDTO.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/time/entries",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<EntryDTO>> getAllEntries(
        
    );


    /**
     * GET /time/consultants : Gets all consultants
     *
     * @return Consultants retrieved (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "getAllEntryConsultants",
        summary = "Gets all consultants",
        tags = { "Time" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Consultants retrieved", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EntryConsultantDTO.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/time/consultants",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<EntryConsultantDTO>> getAllEntryConsultants(
        
    );


    /**
     * GET /time/projects : Gets all projects
     *
     * @return Projects retrieved (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "getAllProjects",
        summary = "Gets all projects",
        tags = { "Time" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Projects retrieved", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EntryProjectDTO.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/time/projects",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<EntryProjectDTO>> getAllProjects(
        
    );


    /**
     * GET /time/entries/{consultantId} : Gets all entries, time bookings for a consultant
     *
     * @param consultantId The ID of the consultant (required)
     * @return Entries retrieved (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "getEntriesByConsultantId",
        summary = "Gets all entries, time bookings for a consultant",
        tags = { "Time" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Entries retrieved", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EntryDTO.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/time/entries/{consultantId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<EntryDTO>> getEntriesByConsultantId(
        @Parameter(name = "consultantId", description = "The ID of the consultant", required = true, in = ParameterIn.PATH) @PathVariable("consultantId") Long consultantId
    );


    /**
     * PUT /time/entries/{consultantId}/{entryId} : update an entry, time bookings for a consultant
     *
     * @param consultantId  (required)
     * @param entryId The ID of the entry (required)
     * @param entryDTO  (required)
     * @return time updated (status code 201)
     */
    @Operation(
        operationId = "updateEntry",
        summary = "update an entry, time bookings for a consultant",
        tags = { "Time" },
        responses = {
            @ApiResponse(responseCode = "201", description = "time updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EntryDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/time/entries/{consultantId}/{entryId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<EntryDTO> updateEntry(
        @Parameter(name = "consultantId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("consultantId") Long consultantId,
        @Parameter(name = "entryId", description = "The ID of the entry", required = true, in = ParameterIn.PATH) @PathVariable("entryId") Long entryId,
        @Parameter(name = "EntryDTO", description = "", required = true) @Valid @RequestBody EntryDTO entryDTO
    );

}
