/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.ostfalia.serp.consultant.api;

import de.ostfalia.serp.consultant.dto.ConsultantDTO;
import de.ostfalia.serp.consultant.dto.Error;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-17T09:47:14.101996026+02:00[Europe/Berlin]")
@Validated
@Tag(name = "Organization", description = "Internal org structure (Consultants & Users)")
public interface ConsultantsApi {

    /**
     * POST /consultants : Creates a consultant in the organization
     *
     * @param consultantDTO  (required)
     * @return Consultant created (status code 201)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "createConsultant",
        summary = "Creates a consultant in the organization",
        tags = { "Organization" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Consultant created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ConsultantDTO.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/consultants",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ConsultantDTO> createConsultant(
        @Parameter(name = "ConsultantDTO", description = "", required = true) @Valid @RequestBody ConsultantDTO consultantDTO
    );


    /**
     * DELETE /consultants/{id} : Remove a consultant by ID
     *
     * @param id  (required)
     * @return Consultant deleted (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "deleteConsultant",
        summary = "Remove a consultant by ID",
        tags = { "Organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Consultant deleted"),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/consultants/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteConsultant(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /consultants/{id} : Gets a consultant by ID
     *
     * @param id  (required)
     * @return Consultant retrieved (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "getConsultant",
        summary = "Gets a consultant by ID",
        tags = { "Organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Consultant retrieved", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ConsultantDTO.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/consultants/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<ConsultantDTO> getConsultant(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /consultants : Gets all consultants in the organization
     *
     * @param shallow  (optional)
     * @return Success (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "getConsultants",
        summary = "Gets all consultants in the organization",
        tags = { "Organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ConsultantDTO.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/consultants",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<ConsultantDTO>> getConsultants(
        @Parameter(name = "shallow", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "shallow", required = false) Boolean shallow
    );


    /**
     * PUT /consultants/{id} : Update a consultant by ID
     *
     * @param id  (required)
     * @param consultantDTO  (required)
     * @return Consultant updated (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "updateConsultant",
        summary = "Update a consultant by ID",
        tags = { "Organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Consultant updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ConsultantDTO.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/consultants/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ConsultantDTO> updateConsultant(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "ConsultantDTO", description = "", required = true) @Valid @RequestBody ConsultantDTO consultantDTO
    );

}
