/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.ostfalia.serp.consultant.api;

import de.ostfalia.serp.consultant.dto.Error;
import de.ostfalia.serp.consultant.dto.UserDTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-17T09:47:14.101996026+02:00[Europe/Berlin]")
@Validated
@Tag(name = "Organization", description = "Internal org structure (Consultants & Users)")
public interface UsersApi {

    /**
     * POST /users : Creates a user in the organization
     *
     * @param userDTO  (required)
     * @return User created (status code 201)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "createUser",
        summary = "Creates a user in the organization",
        tags = { "Organization" },
        responses = {
            @ApiResponse(responseCode = "201", description = "User created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserDTO.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/users",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<UserDTO> createUser(
        @Parameter(name = "UserDTO", description = "", required = true) @Valid @RequestBody UserDTO userDTO
    );


    /**
     * DELETE /users/{id} : Remove a user by ID
     *
     * @param id  (required)
     * @return User deleted (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "deleteUser",
        summary = "Remove a user by ID",
        tags = { "Organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "User deleted"),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/users/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteUser(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /users/{id} : Gets a user by ID
     *
     * @param id  (required)
     * @return User retrieved (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "getUser",
        summary = "Gets a user by ID",
        tags = { "Organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "User retrieved", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserDTO.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<UserDTO> getUser(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /users : Gets all users in the organization
     *
     * @return Success (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "getUsers",
        summary = "Gets all users in the organization",
        tags = { "Organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = UserDTO.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<UserDTO>> getUsers(
        
    );


    /**
     * PUT /users/{id} : Update a user by ID
     *
     * @param id  (required)
     * @param userDTO  (required)
     * @return User updated (status code 200)
     *         or Unexpected Error (status code 200)
     */
    @Operation(
        operationId = "updateUser",
        summary = "Update a user by ID",
        tags = { "Organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "User updated"),
            @ApiResponse(responseCode = "default", description = "Unexpected Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/users/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateUser(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "UserDTO", description = "", required = true) @Valid @RequestBody UserDTO userDTO
    );

}
