spring.application.name=project-service
server.port=${PORT:8084}
debug=false

# =================================
# DATABASE (PostgreSQL)
# =================================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/project_db
spring.datasource.username=${DB_USER:project_user}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# =================================
# OPENAPI / SWAGGER
# =================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=de.ostfalia.serp.project.controller

# =================================
# FIX LOADBALANCER DOCKER
# =================================
# Indique au LoadBalancer où trouver les autres services physiquement
spring.cloud.discovery.client.simple.instances.customer-service[0].uri=http://customer-service:8081
spring.cloud.discovery.client.simple.instances.consultant-service[0].uri=http://consultant-service:8082

# =================================
# RÉSILIENCE (CIRCUIT BREAKER)
# =================================
management.health.circuitbreakers.enabled=true

# 1. Disjoncteur pour Customer Service
resilience4j.circuitbreaker.instances.customerServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.customerServiceCB.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.customerServiceCB.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.customerServiceCB.minimumNumberOfCalls=2

# 2. Disjoncteur pour Consultant Service
resilience4j.circuitbreaker.instances.consultantServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.consultantServiceCB.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.consultantServiceCB.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.consultantServiceCB.minimumNumberOfCalls=2

# =================================
# RÉSILIENCE (RETRY PATTERN)
# =================================
# 1. Retry pour Customer Service (3 tentatives, pause de 2 secondes)
resilience4j.retry.instances.customerServiceRetry.maxAttempts=3
resilience4j.retry.instances.customerServiceRetry.waitDuration=2s

# 2. Retry pour Consultant Service (3 tentatives, pause de 2 secondes)
resilience4j.retry.instances.consultantServiceRetry.maxAttempts=3
resilience4j.retry.instances.consultantServiceRetry.waitDuration=2s

# =================================
# LOGGING
# =================================
logging.level.org.springframework.web=INFO
logging.level.de.ostfalia.serp=DEBUG